[package]
name = "personal-website"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biblatex = "0.8"
indoc = "2.0"
itertools = "0.11.0"
markdown = "1.0.0-alpha.14"
